import { hammingPost } from './posts/hamming-ai'
import { covalPost } from './posts/coval-ai'
import { cekuraPost } from './posts/cekura'
import { roarkPost } from './posts/roark'
import { braintrustPost } from './posts/braintrust'
import { langfusePost } from './posts/langfuse'
import { alternativesPost } from './posts/alternatives-guide'

export const siteConfig = {
  name: 'VaaniEval',
  description: 'Open-source, self-hosted evaluation workspace for production voice-agent conversations.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://www.vaanieval.com',
  appUrl: process.env.NEXT_PUBLIC_APP_URL || 'https://app.vaanieval.com',
  githubUrl: 'https://github.com/shubhamofbce/vaanieval',
  contactUrl: 'https://github.com/shubhamofbce/vaanieval/issues/new?title=Design%20partner%20application&labels=design-partner',
  integrationRequestUrl: 'https://github.com/shubhamofbce/vaanieval/issues/new?title=Integration%20request&body=%23%23%20Integration%20request%0A%0AWhich%20provider%20or%20platform%20would%20you%20like%20VaaniEval%20to%20support%3F%0A%0AWhat%20conversation%20data%20or%20workflow%20should%20it%20support%3F%0A%0APlease%20do%20not%20include%20credentials%2C%20private%20call%20data%2C%20or%20other%20sensitive%20information.',
}

export type BlogPost = {
  slug: string
  title: string
  description: string
  publishedAt: string
  updatedAt?: string
  readingTime: string
  category: string
  content: string[]
}

export const posts: BlogPost[] = [
  hammingPost,
  covalPost,
  cekuraPost,
  roarkPost,
  braintrustPost,
  langfusePost,
  alternativesPost,
  {
    slug: 'evaluate-bolna-voice-agent-calls',
    title: 'How to evaluate Bolna voice-agent calls with VaaniEval',
    description: 'Import Bolna agent executions into a self-hosted workspace and turn call volume and duration into evidence-backed quality scores.',
    publishedAt: '2026-07-18',
    readingTime: '6 min read',
    category: 'Integrations',
    content: [
      'Bolna gives teams a fast path to building and running production voice agents. Like any voice platform, a completed call is not the same thing as a good call: an agent can finish a conversation while giving an unsupported answer, missing a required field, or leaving the caller without a resolved outcome. VaaniEval imports Bolna agent executions into a review workspace so teams can inspect what actually happened on a call, not just that it happened.',
      '## What VaaniEval imports from Bolna',
      'VaaniEval connects to a Bolna account with an API key and pulls the same execution data available through Bolna\'s own API, normalized into one workspace:',
      '- **Agent discovery.** VaaniEval lists the Bolna agents on the connected account so a reviewer can choose which agent\'s calls to bring in.',
      '- **Conversation history.** For a selected agent (or across all agents), VaaniEval fetches executions and supports custom date ranges, including one-click presets such as the last 7, 30, or 90 days.',
      '- **Transcript and outcome.** Each execution\'s transcript, status, summary, and extracted fields are parsed into a normalized conversation record.',
      '- **Telephony and cost metadata.** Call duration, hangup reason, answered-by-voicemail status, and cost breakdown are retained alongside the conversation for context.',
      '- **Call recording.** Where a recording is available, VaaniEval fetches and proxies the audio so reviewers can listen to the call next to its transcript, without needing separate access to the Bolna API.',
      '## From call volume to call quality',
      'A list of executions and their durations answers "how many calls happened" and "how long did they take." It does not answer whether the caller\'s underlying request was actually resolved. VaaniEval adds a reviewable scorecard on top of imported Bolna conversations: task completion, intent understanding, required-information capture, and delivery quality, each backed by a rationale that points to the specific part of the transcript that produced the score.',
      'This distinction matters most in failure cases. A Bolna call can complete cleanly, with a polite agent and no dropped connection, while the caller\'s original task — rescheduling an appointment, resolving a billing question, confirming an order — never actually happened. Reviewing the transcript and recording together, rather than trusting call-completion status alone, is what surfaces that gap.',
      '## What is different about Bolna evidence',
      'Bolna\'s execution detail returns a single formatted transcript string rather than a per-turn array with timestamps. VaaniEval parses that string into individual speaker turns for review, but because Bolna does not expose per-turn start and end times today, turn-level audio scrubbing is not available for Bolna calls the way it is for providers that return timestamped turns. Call-level audio playback and transcript review are still fully supported.',
      'Bolna\'s recording URL also requires the same bearer-token authentication as the rest of its API, so it cannot be linked to directly from a browser. VaaniEval fetches the recording server-side and serves it back through the workspace, so reviewers get a working call player without needing direct API access themselves.',
      '## Setting up the workflow',
      'Connecting Bolna follows the same pattern as other supported providers:',
      '- Add a Bolna API key to the connected workspace.',
      '- Select the Bolna agent (or agents) whose calls should be reviewed.',
      '- Choose a date range and import the matching executions.',
      '- Review transcripts, recordings, and metadata for each conversation.',
      '- Run evaluation scoring and use the rationale and evidence to decide what to fix.',
      'Because VaaniEval is self-hosted, the imported transcripts, recordings, and evaluation results stay in your own database rather than a third-party dashboard, and the same review workflow already used for other providers applies to Bolna calls without a separate tool.',
      '[Set up the Bolna integration](/integrations/bolna)',
      '[Review the voice-agent evaluation metrics guide](/resources/evaluation-metrics)',
      '[Help shape the Bolna workflow as a design partner](/design-partners)',
    ],
  },
  {
    slug: 'voice-agent-qa-production-guide',
    title: 'A practical QA process for production voice agents',
    description: 'How to replace random call sampling with a repeatable conversation review and evaluation workflow.',
    publishedAt: '2026-07-04',
    readingTime: '7 min read',
    category: 'Voice AI QA',
    content: [
      'Voice agents fail in ways that aggregate dashboards hide. A call may complete while the agent gives an unsupported answer, misses an interruption, or leaves the customer without a clear resolution.',
      'A useful QA process starts with production conversations. Import calls continuously, retain transcript and audio context, and evaluate the same small set of business-critical behaviors on every review cycle.',
      'Begin with task completion, unsupported claims, fallback quality, and latency. Define what acceptable evidence looks like for each metric. Review failed conversations with the transcript and audio together, because timing and interruption problems are often invisible in text.',
      'Treat scores as prioritization signals rather than absolute truth. Evaluator rationales should point reviewers to evidence, and uncertain or high-impact cases should remain subject to human review.',
      'Close the loop by grouping repeated failures, assigning an owner, changing the agent, and checking new production calls for regression. The outcome is not a larger dashboard; it is a shorter path from a bad call to a verified fix.',
      '[Use the production voice-agent QA checklist](/resources/voice-agent-qa-checklist)',
      '[Help shape VaaniEval as a design partner](/design-partners)',
    ],
  },
  {
    slug: 'voice-ai-evaluation-metrics',
    title: 'From voice-agent evaluation scores to fixes: a worked example',
    description: 'See how one fictional production call becomes an evidence-backed scorecard, a precise agent change, and a regression check.',
    publishedAt: '2026-07-16',
    readingTime: '6 min read',
    category: 'Evaluation',
    content: [
      'A voice-agent score is useful only when it shortens the path from a weak call to a verified improvement. This worked example follows one fictional appointment-booking conversation through VaaniEval\'s current scorecard: task completion, intent understanding, required-information capture, and human-like delivery.',
      'The conversation is synthetic and deliberately small. It does not represent a customer or a benchmark. Its purpose is to show the reasoning chain a production team can reuse: define the expected outcome, inspect the evidence, identify the weakest behavior, make one targeted change, and evaluate new calls for regression.',
      '## The fictional call',
      '**Caller:** I need to move my dental cleaning to Tuesday morning.',
      '**Agent:** I can help with that. What time on Tuesday works for you?',
      '**Caller:** Anything before eleven.',
      '**Agent:** I am sorry, but I cannot access the scheduling system right now. I am sorry for the inconvenience. Please call us again later and we will help you.',
      '**Caller:** So my existing appointment is still booked?',
      '**Agent:** Please call us again later. Is there anything else I can help you with?',
      'At a glance, the agent understood the request and remained polite. A generic completion dashboard might still classify the call as handled because the intent was detected and the conversation ended normally. The customer outcome tells a different story: no appointment was moved, the original booking was never confirmed, and no safe next step was created.',
      '## Step 1: define success before scoring',
      'For this workflow, task completion should not mean that the agent discussed rescheduling. It should mean that the appointment was moved and the caller received confirmation. If the scheduling tool is unavailable, the approved fallback should preserve the existing booking, capture the caller\'s preferred window and contact details, and create a clear handoff for staff.',
      'This definition matters because an evaluator cannot reliably infer a business outcome from conversational fluency alone. Teams should write the completion condition in operational language that a reviewer can verify from the transcript, tool result, or provider metadata.',
      '## Step 2: score the four current metrics',
      '- **Task completion — 20/100.** The requested appointment change did not happen. The agent also failed to create an alternative path to completion. Evidence: “Please call us again later.”',
      '- **Intent understanding — 90/100.** The agent correctly recognized that the caller wanted to move an existing cleaning to Tuesday before 11:00. The failure occurred after understanding, so rewriting intent detection would not address the main problem.',
      '- **Required-information capture — 35/100.** The agent captured the preferred day and time window but did not confirm the caller\'s identity, the existing appointment, or a callback number. Those fields would be necessary for a human handoff.',
      '- **Human-like delivery — 55/100.** The wording was grammatically clear, but the repeated apology and repeated “call us again later” response made the interaction feel scripted. This is the higher-is-better display score; reviewers should still use the transcript and available audio context before changing delivery behavior.',
      'The scores alone are not the diagnosis. The rationale and conversation evidence explain why the result is weak. In this call, task completion is the weakest business behavior, while the high intent score shows where not to spend engineering time.',
      '## Step 3: map evidence to one targeted change',
      'The primary fix belongs in the scheduling-failure branch, not in the general prompt. When the scheduling tool is unavailable, the agent should follow an explicit recovery sequence:',
      '- State that the appointment has not been changed.',
      '- Confirm whether the existing appointment remains active using available tool state or an approved uncertainty statement.',
      '- Collect the minimum fields required for a staff callback.',
      '- Repeat the requested date and time window back to the caller.',
      '- Create the handoff through the configured workflow, or explain the exact next step if no handoff tool exists.',
      'A revised response might say: “I could not reach the scheduling system, so I have not changed your appointment. I have Tuesday before 11:00 as your preferred window. May I confirm the best callback number so the scheduling team can follow up?”',
      'That response does not pretend the original task succeeded. It makes the system state clear, preserves the caller\'s preference, and moves the conversation toward a recoverable outcome. Whether the agent can actually create the callback must be verified through the configured workflow rather than assumed from the wording.',
      '## Step 4: verify the change without moving the goalposts',
      'After changing the failure branch, keep the original success definition and scorecard stable. Re-run a small representative set that includes a successful reschedule, a scheduling outage, an ambiguous time request, and a caller who declines a callback. Then review new production conversations as they arrive.',
      'For each call, ask:',
      '- Did task completion improve because the outcome improved, or only because the response sounded more confident?',
      '- Did the agent retain correct intent understanding?',
      '- Did it collect only the information required for the handoff?',
      '- Did the new recovery wording reduce repetition without hiding uncertainty?',
      'Compare evaluator judgments with human review on the calls that matter most. If reviewers consistently disagree with the scores, adjust the rubric or evidence requirements before changing thresholds. A threshold is useful only after the team agrees on what the metric means in its own workflow.',
      '## Add broader signals only when they change a decision',
      'Unsupported claims, fallback quality, latency, interruptions, silence, and premature termination can all matter in voice-agent QA. They should be added when the team can define their evidence and connect a failure to an owner. Availability of operational signals also depends on the voice provider and the fields captured for each call.',
      'Start with a small stable scorecard, then segment trends by agent, workflow, provider, and time period. Aggregates identify where performance changed; the individual conversation, rationale, and evidence explain what to fix.',
      '## The reusable score-to-fix loop',
      '- Define the customer and business outcome before evaluating the call.',
      '- Score a small set of distinct behaviors instead of relying on one opaque quality number.',
      '- Attach a rationale and specific conversation evidence to every score.',
      '- Use the weakest relevant behavior to choose one prompt, tool, workflow, or policy change.',
      '- Evaluate representative and new production calls with the same definitions.',
      '- Keep human review for uncertain, high-impact, or disputed results.',
      '[Explore the broader voice-agent evaluation metrics guide](/resources/evaluation-metrics)',
      '[Help shape VaaniEval as a design partner](/design-partners)',
    ],
  },
  {
    slug: 'self-hosted-voice-ai-evaluation',
    title: 'Self-hosted voice-agent evaluation: architecture and tradeoffs',
    description: 'A practical guide to the architecture, data flows, security boundaries, and operating costs of self-hosting voice-agent evaluation.',
    publishedAt: '2026-07-04',
    updatedAt: '2026-07-18',
    readingTime: '8 min read',
    category: 'Self-hosting',
    content: [
      'Self-hosting a voice-agent evaluation system gives your team control over the application environment, database, credentials, and deployment process. It does not automatically make every data flow private or make a deployment compliant with a particular framework.',
      'The useful question is more specific: which components do you operate, where does conversation data travel, and which security and reliability responsibilities move to your team?',
      '## VaaniEval\'s self-hosted architecture',
      'VaaniEval is a full-stack application rather than a library or command-line tool. The repository contains a React review workspace, a FastAPI service, a database-backed queue, a worker, database migrations, and adapters for supported voice and evaluator providers.',
      'A typical evaluation flow has six steps:',
      '- A reviewer connects a supported voice provider.',
      '- The API creates an import job.',
      '- The worker fetches and normalizes conversation transcripts, metadata, and available media references.',
      '- An evaluation job sends conversation context to the configured evaluator provider.',
      '- Metric scores and rationales are stored with the conversation.',
      '- The product workspace presents conversations, evidence, scores, and aggregate trends.',
      'SQLite is available for local use, while the documented production topology uses PostgreSQL shared by the API and worker. The queue is database-backed, so workers need consistent database access and jobs must remain safe to retry.',
      '## What you control',
      'Running VaaniEval in your own environment lets your team choose the application host, network boundaries, database, secrets, allowed origins, provider accounts, evaluator endpoint, backup process, and operational access rules.',
      'The current backend encrypts connected provider credentials before storage and scopes API reads and writes to an authenticated workspace. Production configuration also supports secure cookie settings and explicit allowed origins.',
      'These are useful building blocks, not a complete security program. Your deployment still needs appropriately managed secrets, database encryption and backups, access controls, monitoring, patching, retention rules, and an incident-response process.',
      '## Data that can leave your environment',
      'Self-hosting does not mean conversation data never reaches an external service. The worker communicates with configured voice providers to import calls, and evaluation jobs send conversation context to the evaluator provider selected by the operator.',
      'Before using production data, document each external destination and verify the provider configuration, contract, retention behavior, and permissions that apply to your use case. If a workflow requires stricter boundaries, confirm that the selected providers and deployment topology can support them rather than assuming the application alone provides that guarantee.',
      '## Operational tradeoffs',
      'Self-hosting replaces some vendor dependency with internal operational work:',
      '- **Maintenance:** your team owns upgrades, database migrations, dependency patches, and compatibility testing.',
      '- **Reliability:** the API, worker, and database need health checks, backups, recovery procedures, and enough capacity for import and evaluation jobs.',
      '- **Cost:** infrastructure spend may be predictable, but engineering and on-call time can exceed the hosting bill.',
      '- **Security:** direct control reduces one layer of access, while also making your team responsible for configuration errors, key rotation, auditability, and incident response.',
      '- **Scaling:** larger call volumes increase database growth, queue depth, provider API usage, evaluator cost, and the need for worker concurrency controls.',
      'For a small evaluation program, a single API, worker, and PostgreSQL database may be enough. As volume grows, measure job latency, retries, database load, media access patterns, and evaluator rate limits before adding workers. More concurrency without those controls can amplify provider throttling and duplicate operational load.',
      '## A practical deployment review',
      'Before putting production conversations through a self-hosted evaluation system, verify:',
      '- The API and worker use the same production database.',
      '- Development secrets have been replaced and provider credentials can be rotated.',
      '- Secure cookies, allowed origins, ingress, and administrator access match the intended environment.',
      '- Database backups and migration recovery have been tested.',
      '- Voice-provider and evaluator data flows are documented.',
      '- Retention and deletion behavior covers transcripts, media references, evaluation results, logs, and backups.',
      '- Queue retries, failed jobs, and provider rate limits are observable.',
      '## When self-hosting is a good fit',
      'Self-hosting is most useful when a team needs direct control over deployment and data architecture and has the engineering capacity to operate the stack. A managed path may be more practical when speed and low operational overhead matter more than infrastructure control.',
      'VaaniEval is MIT licensed, so teams can inspect the implementation and adapt provider or evaluation behavior to their workflow. That flexibility also means the operator owns the resulting changes and should test them against representative conversations.',
      '[Explore the open-source VaaniEval architecture](/open-source)',
      '[Review the voice-agent evaluation metrics guide](/resources/evaluation-metrics)',
      '[Help shape the self-hosted workflow as a design partner](/design-partners)',
    ],
  },
]
