import { BlogPost } from '../site'

export const cekuraPost: BlogPost = {
  slug: 'vaanieval-vs-cekura',
  title: 'A Cekura alternative for self-hosted post-call voice-agent QA',
  description: 'Compare Cekura with VaaniEval for teams that need evidence-backed review of completed voice-agent calls and direct control of their deployment.',
  publishedAt: '2026-07-18',
  updatedAt: '2026-07-23',
  readingTime: '8 min read',
  category: 'Alternatives',
  content: [
    'Teams looking for a Cekura alternative usually have a specific question: can we review and improve completed production voice-agent calls while retaining direct control over the application environment and database? VaaniEval is an open-source system designed for that post-call QA workflow. It is not a drop-in replacement for every Cekura capability.',
    'Cekura documents a broader managed platform that includes simulated agent testing and production observability. VaaniEval focuses on importing completed conversations from supported providers, reviewing transcript and available audio evidence, and applying evaluator-backed scorecards. That narrower scope is deliberate: it gives a team a place to move from a weak production call to a specific workflow, prompt, or tool change.',
    '[Read Cekura\'s evaluator overview](https://docs.cekura.ai/documentation/key-concepts/evaluators/overview)',
    '[Read Cekura\'s Vapi observability documentation](https://docs.cekura.ai/documentation/integrations/vapi/observability)',
    '## Open source under AGPL-3.0',
    'VaaniEval is licensed under the GNU Affero General Public License v3.0 (AGPL-3.0-only). Teams may use, copy, modify, deploy, and distribute it under that license. A team that modifies VaaniEval and offers the modified version to users over a network must offer those users the corresponding source code for that version.',
    'The accurate positioning is: **an open-source, self-hosted workspace for post-call voice-agent QA**. AGPL-3.0 is a copyleft license, so it preserves user freedom while requiring network-hosted modified versions to share their source with the users of that version.',
    '## What each product is designed to do',
    '- **Cekura:** Cekura\'s public documentation describes simulated testing through evaluators and production-call observability, including a Vapi integration that can automatically fetch calls. It suits teams seeking a managed platform across testing and monitoring workflows.',
    '- **VaaniEval:** VaaniEval imports completed conversations from ElevenLabs, Vapi, and Bolna through provider adapters. Reviewers can inspect transcripts, available recordings, provider context, evaluator scores, rationales, and quality trends in one workspace.',
    '- **The boundary:** VaaniEval does not claim live call monitoring, pre-deployment conversation simulation, chat-agent testing, CI/CD testing, or real-time alerts. A team that requires those capabilities should validate Cekura or another tool designed for that job.',
    '## A practical post-call QA loop',
    'The VaaniEval workflow begins after a call is complete. A reviewer connects a supported provider, selects a date range or agent, and imports the resulting conversations. The application normalizes the call record so a team can review transcript, metadata, and available media without switching among provider dashboards.',
    'An evaluator-backed scorecard then helps separate distinct questions that a single “call completed” status cannot answer. The current product surfaces task completion, intent understanding, required-information capture, and delivery quality with a rationale tied to the conversation. Teams can also use the workspace to examine resolution quality, unsupported claims, fallback behavior, and available operational signals.',
    'This is most useful when the answer needs evidence. A trend can show that task completion dropped; the individual transcript and recording help a reviewer determine whether the cause was an unclear recovery message, a missing handoff field, a provider failure, or a workflow that the agent could not complete.',
    '## Hosting, data flow, and cost tradeoffs',
    'With VaaniEval, an operator chooses the application host, database, connected provider accounts, evaluator provider, and access controls. That is useful for teams that need control over deployment architecture, but it does not eliminate external data flows: importing calls requires communication with the connected voice provider, and evaluations send conversation context to the evaluator provider selected by the operator.',
    'Self-hosting also moves operational responsibility to the team. The API, worker, database, job retries, backups, secret rotation, observability, retention, and upgrades all need to be operated. At larger call volumes, queue depth, database growth, provider API limits, media access, and evaluator spend need explicit capacity controls. The infrastructure bill may be predictable, but engineering and on-call time can become the larger cost.',
    'A managed product reduces some of that work, while introducing vendor, integration, and data-processing considerations a team should review for its own environment. Neither model is automatically better; the right choice depends on the workflow that must be supported and the operator\'s capacity to run it.',
    '## When VaaniEval is a good Cekura alternative',
    'VaaniEval is a fit when a team wants to investigate completed production calls, retain direct control of a self-hosted deployment, and build a reviewable score-to-fix loop around supported voice providers. It is particularly useful when the priority is turning evidence from real calls into a targeted quality improvement rather than receiving a managed, real-time monitoring service.',
    'It is not the right fit when the team needs pre-launch simulation, chat testing, real-time alerts, or a fully managed operational model. Teams that modify a hosted VaaniEval deployment should also be prepared to meet AGPL-3.0 source-offer obligations. Those requirements should be treated as selection criteria, not glossed over in an alternatives comparison.',
    '## A buyer\'s evaluation checklist',
    '- Define whether the primary job is pre-launch testing, live monitoring, post-call QA, or a combination. A platform can be strong in one workflow without being the best choice for another.',
    '- Map every data destination: voice provider, deployment environment, database, evaluator provider, logs, backups, and any media store.',
    '- Test a representative failure case, not only a successful demo call. Check whether a reviewer can connect an aggregate score to the exact transcript or audio evidence and assign an owner for the fix.',
    '- Budget for the full operating model: subscriptions or infrastructure, evaluator usage, engineering time, support, integrations, and incident response.',
    '- Review the license before deploying. VaaniEval is AGPL-3.0-only, including its source-offer requirement for network-hosted modified versions.',
    '## The bottom line',
    'Cekura and VaaniEval overlap on the goal of improving voice-agent quality, but they serve different operating models. Cekura is documented as a managed platform for testing and observability. VaaniEval is an open-source, self-hosted workspace for evidence-backed QA of completed calls from its supported providers.',
    'If your team wants to explore VaaniEval\'s post-call workflow, inspect the repository and deploy it under AGPL-3.0. If you modify a version that users access over a network, offer them the corresponding source code.',
    '[Explore the self-hosted VaaniEval architecture](/open-source)',
    '[Review the voice-agent evaluation metrics guide](/resources/evaluation-metrics)',
    '[Apply for the 60-day design-partner pilot](/design-partners)',
  ]
}
